#include "mducUDF.h"
#include "udfScalars.h"
#include "udfTools.h"
#include "math.h"

extern udfStruct udf;
static double Sc_t = 0.7; /* turbulent Schmidt number */

/* --------------- FLUENT source and flux definitions ---------------------- */
/*                                                                           */
/*   This file defines all the necessary terms for the solution of           */
/*   additional scalar equations required the by the MDUC in Fluent.         */
/*   The terms required are:                                                 */
/*     turbulent diffusivity (DEFINE_DIFFUSIVITY)                            */
/*     source (DEFINE_SOURCE)                                                */
/*                                                                           */
/*   The scalar equations defined here include:                              */
/*     total enthlalpy:              Htot_src, H_var                         */
/*     mixture fraction of fuel 1:   Diff_Z1, Z1_src, Z1var_src              */
/*     mixture fraction of fuel 2:   Diff_Z2, Z2_src, Z2var_src              */
/*     mixture fraction of oxidator: Diff_Z,  Z_src,  Zvar_src               */
/*                                                                           */
/* ------------------------------------------------------------------------- */

/*
  Source term for the total enthalpy to be tracked as a user-defined-scalar
  in FLUENT.  This is necessary to be able to update the total enthalpy in the 
  reactive case.

  Description of source terms:

  C_DPMS_ENERGY is the heat transfer term from fluent that accounts for the
  heat up and evaporation of the droplet based on the fluid properties
  specified.  This is roughly equivalent to:
     Q = delta(H)_vap - cp_L*(T_L - T_ref)
  The term is more accurate than computing because it includes heat up 
  without evaporation.

  DPDT, the pressure rate, is self-explanatory.

  H_vap is the enthalpy of the fuel vapour that is generated by the droplet,
  hence it is multiplied by the mass source from the droplet.  This is
  computed as the enthalpy of the evaporated species at the reference
  temperature corresponding to the enthalpy of vaporisation used.  According
  to Fluent, the reference temperature used is the boiling temperature.
     H_vap = sum_i[Y_i*h_i(T_ref)]

  NOTE: H_vap is for n-heptane, not diesel, and is computed once during
        initialisation as a static global variable

  units: [J/(m^3-s)]
*/
DEFINE_SOURCE(Htot_src, c, t, dS, eqn) 
{
  double w;
  w = udf.dPdt;
  if (udf.injection > 0 && sg_dpm)
    w+=(C_DPMS_ENERGY(c,t)+udf.H_vap_ref*C_SOURCE_MASS_DPM(c,t))/C_VOLUME(c,t);

  return w;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(PROG_TOTAL_src, c, t, dS, eqn)
{
  double w;
  /* return the progress variable from the table looked-up in update routine */
  
  /* return the maximum progress variable source term of FPVA and RIF model */
  w = C_RIFSRC(c,t);
  return w;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(Hmod_src, c, t, dS, eqn) 
{
  int j;
  double src, src_localZ;
  if (udf.injection == 0)
    src = udf.dPdt;
  else
    src = udf.dPdt + (C_DPMS_ENERGY(c,t) +
                      udf.H_vap_ref*C_SOURCE_MASS_DPM(c,t))/C_VOLUME(c,t);

  /* apply the conditional source term */
  /* TODO: generalize this for mixture */
  j = UDFgridLocate(udf.nCondZ, udf.condZ, C_Z1MEAN(c,t));

  if (C_Z1MEAN(c,t) < 0.5*(udf.condZ[j]+udf.condZ[j+1])) {
    src_localZ = udf.src_condZ[j];
  }
  else {
    src_localZ = udf.src_condZ[j+1];
  }

  return src - src_localZ;
}
/* ------------------------------------------------------------------------- */

/* standard definition of turbulent diffusivity */
DEFINE_DIFFUSIVITY(Diffusivity, c, t, i)
{
  return (2.88E-05 + C_MU_T(c,t))/Sc_t;
}
/* ------------------------------------------------------------------------- */

DEFINE_DIFFUSIVITY(Diff_Z1, c, t, i)
{
#ifdef MDUC_SPRAY
  return C_FDT_1(c,t)*C_MU_T(c,t)/Sc_t;
#else
  return C_MU_T(c,t)/Sc_t;
#endif
}
/* ------------------------------------------------------------------------- */

DEFINE_DIFFUSIVITY(Diff_Z2, c, t, i)
{
#ifdef MDUC_SPRAY
  return C_FDT_2(c,t)*C_MU_T(c,t)/Sc_t;
#else
  return C_MU_T(c,t)/Sc_t;
#endif
}
/* ------------------------------------------------------------------------- */

DEFINE_DIFFUSIVITY(Diff_Z, c, t, i)
{
#ifdef MDUC_SPRAY
  return C_FDT_0(c,t)*C_MU_T(c,t)/Sc_t;
#else
  return C_MU_T(c,t)/Sc_t;
#endif
}
/* ------------------------------------------------------------------------- */

DEFINE_DIFFUSIVITY(Diff_EGR, c, t, i)
{
  return C_MU_T(c,t)/Sc_t;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(Z_src, c, t, dS, eqn)
{
  if (sg_dpm)
    return C_SOURCE_MASS_DPM(c,t)/(C_VOLUME(c,t));
  return 0.;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(Z1_src, c, t, dS, eqn)
{
  /* C_FUEL1_SRC is set in the header file to C_DPMS_YI(c,t,<fuel1 index>)
     units: [kg/(m^3-s)] */
  if (sg_dpm)
    return C_FUEL1_SRC(c,t)/(C_VOLUME(c,t));
  return 0.;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(Z2_src, c, t, dS, eqn)
{
 /* C_FUEL2_SRC is set in the header file to C_DPMS_YI(c,t,<fuel2 index>)
     units: [kg/(m^3-s)] */
  if (sg_dpm)
    return C_FUEL2_SRC(c,t)/(C_VOLUME(c,t));
  return 0.;
}
/* ------------------------------------------------------------------------- */

/*
 Variance models are based on:
     dVar/dt = -C1*rho*chi*Var + C2*mu_t/Sc*grad(Mean)  :  [kg/(m^3-s)]
*/
DEFINE_SOURCE(Zvar_src, c, t, dS, eqn)
{
  double w;         /* source term to return */
  double GradZ[3];  /* for storing sum of gradients */
  double C_x = 2.0; /* constant representing tau/tau_z */
  double C_eps;     /* multiplier for variance in dissipation term */
 
  GradZ[0] = (C_Z1MEAN_G(c,t)[0] + C_Z2MEAN_G(c,t)[0]); 
  GradZ[1] = (C_Z1MEAN_G(c,t)[1] + C_Z2MEAN_G(c,t)[1]); 
  GradZ[2] = (C_Z1MEAN_G(c,t)[2] + C_Z2MEAN_G(c,t)[2]);

#ifdef MDUC_SPRAY  /* include evaporative src terms */
#ifdef MDUC_SPRAY_LINEAR
  /* use Hasse's linearised formulation for source terms */
  C_eps =   C_R(c,t)*(C_Z0VAR_EPS(c,t) - C_Z0VAR_SRC(c,t));
  w     =   2.0*C_FDT_0(c,t)*C_MU_T(c,t)/Sc_t*NV_MAG2(GradZ)
          - C_eps*C_Z0VAR(c,t);
#else
  /* use standard SDM model from Reveillon and Vervisch (non-linearised) */
  C_eps =   C_R(c,t)*C_Z0VAR_EPS(c,t);
  w     =   2.0*C_FDT_0(c,t)*C_MU_T(c,t)/Sc_t*NV_MAG2(GradZ)         /* prod. */
          - C_eps*C_Z0VAR(c,t)                                       /* diss. */
          + C_R(c,t)*C_Z0VAR_SRC(c,t);                               /* evap. */
#endif  /* MDUC_SPRAY_LINEAR */
#else
  /* no spray, use standard variance equation */
  C_eps =   C_x*C_R(c,t)*C_D(c,t)/(C_K(c,t)+1.e-6);
  w     =   2.0*C_MU_T(c,t)/Sc_t*NV_MAG2(GradZ)
            - C_eps*C_Z0VAR(c,t);
#endif /* MDUC_SPRAY */

  dS[eqn] = - C_eps; /* derivative with respect to Z0VAR */

  return w;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(Z1var_src, c, t, dS, eqn)
{
  double w;         /* source term to return */
  double C_x = 2.0; /* constant representing tau/tau_z */
  double C_eps;     /* multiplier for variance in dissipation term */

#ifdef MDUC_SPRAY  /* include evaporative src terms */
#ifdef MDUC_SPRAY_LINEAR
  /* use Hasse's linearised formulation for source terms */
  C_eps =   C_R(c,t)*(C_Z1VAR_EPS(c,t) - C_Z1VAR_SRC(c,t));
  w     =   2.0*C_FDT_1(c,t)*C_MU_T(c,t)/Sc_t*NV_MAG2(C_Z1MEAN_G(c,t))
          - C_eps*C_Z1VAR(c,t);
#else
  /* use standard SDM model from Reveillon and Vervisch (non-linearised) */
  C_eps =   C_R(c,t)*C_Z1VAR_EPS(c,t);
  w     = 2.0*C_FDT_1(c,t)*C_MU_T(c,t)/Sc_t*NV_MAG2(C_Z1MEAN_G(c,t)) /* prod. */
          - C_eps*C_Z1VAR(c,t)                                       /* diss. */
          + C_R(c,t)*C_Z1VAR_SRC(c,t);                               /* evap. */
#endif  /* MDUC_SPRAY_LINEAR */
#else
  /* no spray, use standard variance equation */
  C_eps = C_x*C_R(c,t)*C_D(c,t)/(C_K(c,t)+1.e-6);
            /* production */                              /* dissipation */
  w     = C_x*C_MU_T(c,t)/Sc_t*NV_MAG2(C_Z1MEAN_G(c,t)) - C_eps*C_Z1VAR(c,t);
#endif /* MDUC_SPRAY */

  dS[eqn] = - C_eps; /* derivative with respect to Z1VAR */

  return w;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(Z2var_src, c, t, dS, eqn)
{
  double w;         /* source term to return */
  double C_x = 2.0; /* constant representing tau/tau_z */
  double C_eps;     /* multiplier for variance in dissipation term */
 
#ifdef MDUC_SPRAY  /* include evaporative src terms */
#ifdef MDUC_SPRAY_LINEAR
  /* use Hasse's linearised formulation for source terms */
  C_eps =   C_R(c,t)*(C_Z2VAR_EPS(c,t) - C_Z2VAR_SRC(c,t));
  w     =   2.0*C_FDT_2(c,t)*C_MU_T(c,t)/Sc_t*NV_MAG2(C_Z2MEAN_G(c,t))
          - C_eps*C_Z2VAR(c,t);
#else
  /* use standard SDM model from Reveillon and Vervisch (non-linearised) */
  C_eps =   C_R(c,t)*C_Z2VAR_EPS(c,t);
  w     = 2.0*C_FDT_2(c,t)*C_MU_T(c,t)/Sc_t*NV_MAG2(C_Z2MEAN_G(c,t)) /* prod. */
          - C_eps*C_Z2VAR(c,t)                                       /* diss. */
          + C_R(c,t)*C_Z2VAR_SRC(c,t);                               /* evap. */
#endif /* MDUC_SPRAY_LINEAR */
#else
  /* no spray, use standard variance equation */
  C_eps = C_x*C_R(c,t)*C_D(c,t)/(C_K(c,t)+1.e-6);
            /* production */                              /* dissipation */
  w     = C_x*C_MU_T(c,t)/Sc_t*NV_MAG2(C_Z2MEAN_G(c,t)) - C_eps*C_Z2VAR(c,t);
#endif /* MDUC_SPRAY */

  dS[eqn] = - C_eps; /* derivative with respect to Z2VAR */

  return w;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(EGRvar_src, c, t, dS, eqn)
{
  double w;         /* source term to return */
  double C_x = 2.0; /* constant representing tau/tau_z */
  double C_eps;     /* multiplier for variance in dissipation term */
 
  /* no spray, use standard variance equation */
  C_eps = C_x*C_R(c,t)*C_D(c,t)/(C_K(c,t)+1.e-6);
            /* production */                              /* dissipation */
  w     = C_x*C_MU_T(c,t)/Sc_t*NV_MAG2(C_EGR_G(c,t)) - C_eps*C_EGRVAR(c,t);

  dS[eqn] = - C_eps; /* derivative with respect to Z2VAR */

  return w;
}
/* ------------------------------------------------------------------------- */

DEFINE_SOURCE(Hvar_src, c, t, dS, eqn)
{
  double w;         /* source term to return */
  double C_x = 2.0; /* constant representing tau/tau_z */
  double C_eps;     /* multiplier for variance in dissipation term */
  double g = C_GAMMA(c,t);
  return 0.0;
  /* no spray, use standard variance equation */
/*   C_eps =   C_x*C_R(c,t)*C_D(c,t)/(C_K(c,t)+1.e-6)   /\* dissipation *\/ */
/*           + 2*(g-1)/g*C_R(c,t)/udf.PAvg*udf.dPdt;    /\* source *\/ */

  C_eps =   C_x*C_R(c,t)*C_D(c,t)/(C_K(c,t)+1.e-6);   /* dissipation */

                /* production */               /* dissipation and source */     
  w = C_x*C_MU_T(c,t)/Sc_t*NV_MAG2(C_HTOT_G(c,t)) - C_eps*C_HVAR(c,t); 

  dS[eqn] = - C_eps; /* derivative with respect to HVAR */

  return w;
}
/* ------------------------------------------------------------------------- */

/*
  Defines the heat flux across the faces
*/
DEFINE_PROFILE(H_FLUX, t, i)
{
  double A[ND_ND], A_f;
  face_t f;   

  /* loop over all faces */
  begin_f_loop(f,t) {
    /* ensure faces not counted twice at partition boundaries, always true
       in serial */
    if (PRINCIPAL_FACE_P(f,t)) {
      F_AREA(A, f, t);
      A_f = NV_MAG(A);
      
      F_PROFILE(f,t,i) = BOUNDARY_HEAT_FLUX(f,t)/A_f;  /* W/m^2 */
    }
  } end_f_loop(f,t);
}
/* ------------------------------------------------------------------------- */

/* Heat Flux Han & Reitz*/
/*
  Defines the heat flux across the faces
*/
DEFINE_PROFILE(H_FLUX_Han, t, i)
{
  double y,yPlus,kinE,uTau,T,Tw,rho,cp,q,nu;
  double Cmu=0.09;
  double A[ND_ND],ds,es[ND_ND],A_by_es,dr0[ND_ND];
  face_t f;   
  Thread *t0;
  cell_t  c0;

  /* loop over all faces */
  begin_f_loop(f,t) {
    t0 = THREAD_T0(t);
    c0 = F_C0(f,t);
    BOUNDARY_FACE_GEOMETRY(f,t,A,ds,es,A_by_es,dr0);
    y   = NV_DOT(dr0,A);
    y   /= NV_MAG(A);
    rho  = C_R(c0,t0);               /* density from adjacent cell */
    T    = C_T(c0,t0);               /* temperature from adjacent cell */
    cp   = C_CP(c0,t0);              /* specific heat from adjacent cell */
    nu   = C_MU_L(c0,t0)/C_R(c0,t0); /* kinematic viscosity from adjacent cell */
    kinE = C_K(c0,t0);               /* turb. kin. energy from adjacent cell */
    Tw   = F_T(f,t);                 /* wall temperature */
    /* get T from Face */   
    /* heat flux calculation */
    uTau  = pow(Cmu,0.25)*pow(kinE,0.5);
    yPlus = y*uTau/nu;       
    
    q   = -(rho*cp*uTau*T*log(T/Tw))/(2.1*log(yPlus)+2.5);	
    /* ensure faces not counted twice at partition boundaries, always true
       in serial */
    F_PROFILE(f,t,i) = q; /* W/m^2 */
  } end_f_loop(f,t);
}
/* ------------------------------------------------------------------------- */

void UDFsetScalarDefaultSources(Domain *d)
{
  Thread *t;
  cell_t c;

  int i;
  double tau;        /* turbulent time scale [s]  */
  double C_x = 2.0;  /* time scale constant */

  /* loop over all cells to set to zero/default */
  thread_loop_c(t,d) {
    begin_c_loop_int(c,t) {
      tau  = C_K(c,t)/(C_D(c,t)+1.0e-6);

      for (i=0; i<3; i++) {
        if (udf.iFuelV[i] >= 0)  /* fuel volume */
          C_UDMI(c,t,udmOffset+udf.iFuelV[i])  = 0.0;
        if (udf.iZV_SRC[i] >= 0) /* variance source */
          C_UDMI(c,t,udmOffset+udf.iZV_SRC[i]) = 0.0;
        if (udf.iZV_EPS[i] >= 0) /* variance dissipation */
          C_UDMI(c,t,udmOffset+udf.iZV_EPS[i]) = C_x/tau;
        if (udf.iFDT[i] >= 0)    /* diffusion coefficient */
          C_UDMI(c,t,udmOffset+udf.iFDT[i])    = 1.0;
      }
#if DEBUG_SDM
      for (i=0; i<3; i++) {
        if (udf.iZV_PRD[i] >= 0)
          C_UDMI(c,t,udmOffset+udf.iZV_PRD[i]) = 0.0;
        if (udf.iXI[i] >= 0)
          C_UDMI(c,t,udmOffset+udf.iXI[i])     = 0.0;
        if (udf.iAlphaB[i] >= 0)
          C_UDMI(c,t,udmOffset+udf.iAlphaB[i]) = 0.0;
      }
      C_SPALD_NO(c,t) = 0.0;
#endif DEBUG_SDM
    } end_c_loop_int(c,t);
  }
}
/* ------------------------------------------------------------------------- */

void UDFsetScalarIndex()
{
  int i;
  /* read in from the scalar mapping from input file */
  udf.nUDS = -1;
  if (RP_is_Defined("mduc/scalars")) {
    udf.nUDS = parseFluentString(RP_Get_String("mduc/scalars"),
                                 &udf.udsNames);
    for (i=0; i<udf.nUDS; i++)
      UDFstripStringBraces(udf.udsNames[i]);
  }

  udf.iZ1  = udf.iZ1V  = -1;
  udf.iZ2  = udf.iZ2V  = -1;
  udf.iZ0V = -1;
  udf.iEGR = udf.iEGRV = udf.iProg = -1;
  udf.iH   = udf.iHV   = udf.iHMOD = -1;
  udf.iProgTotal = -1;

  /* map scalars according to key found below */
  if (udf.nUDS == 0) { /* set the default configuration */
    Message0("  Setting default scalar configuration\n");
    udf.nUDS = 6;
    udf.iZ1 = 0; udf.iZ1V = 1;
    udf.iZ2 = 2; udf.iZ2V = 3; udf.iZ0V = 4;
    udf.iH  = 5; udf.iHV  = 6;
    udf.udsNames = (char**) calloc(udf.nUDS, sizeof(char*));
    for (i=0; i<udf.nUDS; i++)
      udf.udsNames[i] = (char*) calloc(32, sizeof(char));

    strcpy(udf.udsNames[udf.iZ1],  "Z1-mean");
    strcpy(udf.udsNames[udf.iZ1V], "Z1-variance");
    strcpy(udf.udsNames[udf.iZ2],  "Z2-mean");
    strcpy(udf.udsNames[udf.iZ2V], "Z2-variance");
    strcpy(udf.udsNames[udf.iZ0V], "Z0-variance");
    strcpy(udf.udsNames[udf.iH],   "H-mean");
  }
  else {
    for (i=0; i<udf.nUDS; i++) {
      if (!strncmp(udf.udsNames[i], "Z1-m", 4))          udf.iZ1    = i;
      else if (!strncmp(udf.udsNames[i], "Z1-v", 4))     udf.iZ1V   = i;
      else if (!strncmp(udf.udsNames[i], "Z2-m", 4))     udf.iZ2    = i;
      else if (!strncmp(udf.udsNames[i], "Z2-v", 4))     udf.iZ2V   = i;
      else if (!strncmp(udf.udsNames[i], "Z0-v", 4) ||
               !strncmp(udf.udsNames[i], "Z-v",  3))     udf.iZ0V   = i;
      else if (!strncmp(udf.udsNames[i], "EGR-m", 5))    udf.iEGR   = i;
      else if (!strncmp(udf.udsNames[i], "EGR-v", 5))    udf.iEGRV  = i;
      else if (!strncmp(udf.udsNames[i], "H-m", 3))      udf.iH     = i;
      else if (!strncmp(udf.udsNames[i], "H-v", 3))      udf.iHV    = i;
      else if (!strncmp(udf.udsNames[i], "Hmod", 4))     udf.iHMOD  = i;
      else if (!strcmp(udf.udsNames[i],  "C-prog"))      udf.iProg  = i;
      else if (!strncmp(udf.udsNames[i], "C-prog-v", 8)) udf.iProgV = i;
      else if (!strncmp(udf.udsNames[i], "C-prog-total", 10))
        udf.iProgTotal = i;
    } /* end loop over scalars */
  }

  Message0("  Scalars for MDUC library (%i):\n", udf.nUDS);
  for (i=0; i<udf.nUDS; i++)
    Message0("   %3i %32s\n", i, udf.udsNames[i]);
}
/* ------------------------------------------------------------------------- */
