import sys
import numpy as np
from matplotlib import pyplot as plt

#data = np.loadtxt(sys.argv[1],comments="x", delimiter="   ", unpack=False)
data = np.loadtxt(sys.argv[1],comments="#",unpack=False)
SOI = 0.2 # 0.3333

plt.plot(data[:,0],data[:,2], lw=2, label='Y_l')
plt.plot(data[:,0],data[:,3], lw=2, label='Y_v')
plt.plot(data[:,0],data[:,4], lw=2, label='Y_a')
plt.ylabel('Mass Fraction')
plt.xlabel('z/D [-]')
legend = plt.legend(loc='upper right', shadow=True)
plt.savefig('mass_fraction.pdf', bbox_inches='tight')
plt.show()

plt.clf()
plt.plot(data[:,0],data[:,1], lw=2, label='\rho')
plt.plot(data[:,0],data[:,6], lw=2, label='u_l')
plt.plot(data[:,0],data[:,7], lw=2, label='u_g')
plt.plot(data[:,0],data[:,12], lw=2, label='T_d')
plt.plot(data[:,0],data[:,10], lw=2, label='T_g')
plt.ylabel('Flow Variables')
plt.xlabel('z/D [-]')
legend = plt.legend(loc='upper right', shadow=True)
plt.savefig('flow_variables.pdf', bbox_inches='tight')
plt.show()

plt.clf()
ax = plt.gca()
ax2 = ax.twinx()
plt.axis('normal')
ax.plot(data[:,0],data[:,8], color='red', lw=2, label='<dm>')
ax.set_ylabel("Mean of Diameter",fontsize=14,color='red')
ax2.plot(data[:,0],data[:,9], color='blue', lw=2, label='<d2>')
ax2.set_ylabel("Second Moment of Diameter",fontsize=14,color='blue')
ax.set_ylabel("Mean of Diameter",fontsize=14,color='red')
#ax.set_ylim(ymax=100)
#ax.set_xlim(xmax=100)
#ax.grid(True)
plt.title("Droplet Diameter", fontsize=20,color='black')
ax.set_xlabel('z/D [-]', fontsize=14, color='b')
legend = plt.legend(loc='upper right', shadow=True)
plt.savefig('droplet_diameter.pdf', bbox_inches='tight')
plt.show()

plt.clf()
SPL = np.loadtxt("PL.out", comments="#", unpack=False)
ELPL = np.genfromtxt("Liq_ome4_1000bar_100bar_850K.dat", comments="x", unpack=False)
EVPL = np.genfromtxt("Vap_ome4_1000bar_100bar_850K.dat", comments="x", unpack=False)
plt.plot(SPL[:,1],SPL[:,2], color='blue', lw=2, label='Sim: LPL')
plt.plot(ELPL[:,0]-SOI,ELPL[:,1], linestyle="None",marker='s',mfc='None',mec='blue',mew=1, label='Exp: LPL')
plt.plot(SPL[:,1],SPL[:,3], color='red', lw=2, label='Sim: VPL')
plt.plot(EVPL[:,0]-SOI,EVPL[:,1], linestyle="None",marker='o',mfc='None',mec='red',mew=1, label='Exp: VPL')
plt.ylabel('Spray Penetration Length [mm]')
plt.xlabel('time [ms]')
plt.title('Spray Penetration Vs Time')
plt.xlim([0,2.5])
plt.ylim([0,80.0])
legend = plt.legend(loc='upper left', shadow=True)
plt.savefig('PL_sim_exp.pdf', bbox_inches='tight')
plt.show()

plt.clf()
SPL1d = np.loadtxt("PL_1d.out", comments="x", unpack=False)
SPL2d = np.loadtxt("PL_2d.out", comments="x", unpack=False)
SPL4d = np.loadtxt("PL_4d.out", comments="x", unpack=False)
SPL8d = np.loadtxt("PL_8d.out", comments="x", unpack=False)
ELPL = np.loadtxt("Liq_ome4_1000bar_100bar_850K.dat", comments="x", unpack=False)
plt.plot(SPL1d[:,0],SPL1d[:,1], color='blue', lw=2, label='Sim LPL: grid dz=1xD')
plt.plot(SPL2d[:,0],SPL2d[:,1], color='blue', ls='--', lw=2, label='Sim LPL: grid dz=2xD')
plt.plot(SPL4d[:,0],SPL4d[:,1], color='blue', ls='-.', lw=2, label='Sim LPL: grid dz=4xD')
plt.plot(SPL8d[:,0],SPL8d[:,1], color='blue',  lw=1, label='Sim LPL: grid dz=8xD')
plt.plot(ELPL[:,0]-SOI,ELPL[:,1], linestyle="None",marker='s',mfc='None',mec='blue',mew=1,markevery=1, label='Exp: LPL')
plt.ylabel('Spray Penetration Length [mm]')
plt.xlabel('time [ms]')
plt.title('Spray Penetration Vs Time')
plt.xlim([0,1.0])
plt.ylim([0,30.0])
legend = plt.legend(loc='lower right', shadow=True)
plt.savefig('LPL_mesh_convergence.pdf', bbox_inches='tight')
plt.show()

plt.clf()
SPL1d = np.loadtxt("PL_1d.out", comments="x", unpack=False)
SPL2d = np.loadtxt("PL_2d.out", comments="x", unpack=False)
SPL4d = np.loadtxt("PL_4d.out", comments="x", unpack=False)
SPL8d = np.loadtxt("PL_8d.out", comments="x", unpack=False)
EVPL = np.loadtxt("Vap_ome4_1000bar_100bar_850K.dat", comments="x", unpack=False)
plt.plot(SPL1d[:,0],SPL1d[:,2], color='red', lw=2, label='Sim VPL: grid dz=1xD')
plt.plot(SPL2d[:,0],SPL2d[:,2], color='red', ls='--', lw=2, label='Sim VPL: grid dz=2xD')
plt.plot(SPL4d[:,0],SPL4d[:,2], color='red', ls='-.', lw=2, label='Sim VPL: grid dz=4xD')
plt.plot(SPL8d[:,0],SPL8d[:,2], color='red', lw=1, label='Sim VPL: grid dz=8xD')
plt.plot(EVPL[:,0]-SOI,EVPL[:,1], linestyle="None",marker='o',mfc='None',mec='red',mew=1,markevery=1, label='Exp: VPL')
plt.ylabel('Spray Penetration Length [mm]')
plt.xlabel('time [ms]')
plt.title('Spray Penetration Vs Time')
plt.xlim([0,1.0])
plt.ylim([0,60.0])
legend = plt.legend(loc='lower right', shadow=True)
plt.savefig('VPL_mesh_convergence.pdf', bbox_inches='tight')
plt.show()
