#ifndef MDUC_FILE_IO_H
#define MDUC_FILE_IO_H

#include "mducStructs.h"
#include "pdf_parameters.h"

void createDataFileName(const char *fileName, ioStruct *io, timeStruct *time, 
                        char *dataFileName);
void steadyFlameletFileName(const char *fileName, ioStruct *io,flowStruct *flow,
                            char *dataFileName);

void checkMonitor(ioStruct *io);
int  checkFileExists(char *fileName);

/* ----- MDUC functions to read/write flamelet and init files ----- */
void readInitFile(ioStruct *io, driveStruct *driver, timeStruct *time,
                  flameStruct *flame, flowStruct *flow, sdialStruct *sdial,
                  engineStruct *engine);

void readFlamelet(char *flameFile, ioStruct *io, driveStruct *driver, 
                  timeStruct *time, flameStruct *flame, flowStruct *flow);
void readChi(char *flameFile, ioStruct *io, int i);

double readFlowData(char *fileName, driveStruct *driver, flowStruct *flow);
double readFileTime(char *fileName);
double readFileScalar(char *fileName, char *varName);

void readVariableArray(char *fileName, char *varName, double **var);

void writeFlamelet(char *fileName, ioStruct *io, driveStruct *driver, 
                   timeStruct *time,flameStruct *flame, flowStruct *flow);

void readRates(char *fileName, chemStruct *chem); 
void writeRates(char *fileName, chemStruct *chem); 

void writeFlowData(char *fileName, ioStruct *io, driveStruct *driver,
                   timeStruct *time, flameStruct *flame, flowStruct *flow);

int readTabFileVar(char *fileName, int iT, double **time, int iV, double **var);

void addVarToBody(char *fileName, int n1, int n2, double *var, char *varName);

void writeSolution(char *fileName, ioStruct *io, chemStruct *chem,
                   flameStruct *flame);

void writeInitSolution(char *fileName, ioStruct *io, flameStruct *flame);

void writeArray(FILE *pFile, int m, int n, int offset, int index, int newLine, 
                double *data);

int readTabFileVar(char *fileName, int iT, double **time, int iV, double **var);

// write the header for the scalars file
void writeScalarsHeader(driveStruct *driver, ioStruct *io);
int  truncateFileTime(char *fileName, double t_end);

// these should eventually moved to utitilities file
void stripHeader(char *str);

// functions for dealing with NGA data files
void NGA_printFileInfo(char *file);

void NGA_readInfo(FILE *pFile, int *nx, int *ny, int *nz, int *nVars,
                  char ***varNames, double *t, double *dt);

void NGA_readData(char *file, int *nx, int *ny, int *nz, char *varName,
                 double ****var, double *t, double *dt);

void NGA_readDataAll(char *file, int *nx, int *ny, int *nz, int *nVars,
                    char ***varNames, double *****vars, double *t, double *dt);

/* ----- functions for reading tables generated by NIST ----- */
void NIST_getThermo(char *fileName, double *hfg, double *cpG, double *cpL,
                    double *Psat, double T);

/* ----- function for writing Ensight data/case files ----- */
void initEnsight(ioStruct *io, flowStruct *flow);

void writeEnsightGeom(ioStruct *io, driveStruct *driver, timeStruct *time,
                      flameStruct *flame, flowStruct *flow);

void writeEnsightCaseHead(ioStruct *io, driveStruct *driver, timeStruct *time,
                          flameStruct *flame, flowStruct *flow);

void writeEnsightData(char *fileName, char *varName, int m, int n,
                      int offset, int index, double *data);

void updateEnsightCaseTime(double newTime, ioStruct *io, timeStruct *time);

void writeBinaryArrayReal(FILE *pFile, int n, double *val);

/* read/write arbitrary array as binary data */
int  binaryFileRead(void *buffer, int size, int count, FILE *pFile);
int  binaryFileWrite(void *buffer, int size, int count, FILE *pFile);

#endif /* MDUC_FILE_IO_H */
